method: conv_onet
data:
  dataset: Shapes3D
  path: data/ShapeNet
  watertight_path: data/watertight
  classes: null
  input_type: img
  train_split: train
  val_split: val
  test_split: test
  dim: 3
  points_file: points.npz
  points_iou_file: points.npz
  multi_files: null
  points_subsample: 1024
  points_unpackbits: true
  model_file: model.off
  watertight_file: model_watertight.off
  img_folder: img
  img_size: 224 
  img_with_camera: false
  img_augment: false
  n_views: 24
  pointcloud_file: pointcloud.npz
  pointcloud_chamfer_file: pointcloud.npz
  pointcloud_n: 256
  pointcloud_target_n: 1024
  pointcloud_noise: 0.05
  voxels_file: 'model.binvox'
  padding: 0.1
model:
  decoder: simple
  encoder: resnet18
  decoder_kwargs: {}
  encoder_kwargs: {}
  multi_gpu: false
  c_dim: 512
training:
  out_dir:  out/default
  batch_size: 64
  print_every: 200
  visualize_every: 1000
  checkpoint_every: 1000
  validate_every: 2000
  backup_every: 100000
  eval_sample: false
  model_selection_metric: loss
  model_selection_mode: minimize
  n_workers: 4
  n_workers_val: 4
test:
  threshold: 0.5
  eval_mesh: true
  eval_pointcloud: true
  remove_wall: false
  model_file: model_best.pt
generation:
  batch_size: 100000
  refinement_step: 0
  vis_n_outputs: 30
  generate_mesh: true
  generate_pointcloud: true
  generation_dir: generation
  use_sampling: false
  resolution_0: 32
  upsampling_steps: 2
  simplify_nfaces: null
  copy_groundtruth: false
  copy_input: true
  latent_number: 4
  latent_H: 8
  latent_W: 8
  latent_ny: 2
  latent_nx: 2
  latent_repeat: true
  sliding_window: False # added for crop generation