inherit_from: configs/pointcloud/room_grid64.yaml
generation:
  generation_dir: generation_pretrained
test:
  model_file: https://s3.eu-central-1.amazonaws.com/avg-projects/convolutional_occupancy_networks/models/pointcloud/room_grid64.pt
